### ISSUE TITLE
Thanks for creating!

### ISSUE THREAD

**Issue by cameronelliott** [Industrial/test-oak#1]
Hey, I hope you don't mind the spurious issues. Please feel free to close.
I think there is a need for Deno/React/Oak, so thanks for creating this!
Please feel free to close.

**Comment by Industrial** [comment]
Hi!

You're welcome!

I have no solution yet for deployment (so "dev" mode only at the moment) but that will come soon :)

You could hang out on [Discord](https://discord.gg/CvPVVeVk) if you like
